In [1]:
!uv add pandas

Resolved 114 packages in 1.06s
Prepared 2 packages in 745ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 1.19s
 + numpy==2.4.6
 + pandas==3.0.3

In [3]:
import pandas as pd

In [4]:
prefix = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/"
df = pd.read_csv(prefix + "yellow_tripdata_2020-02.csv.gz", nrows=100)

In [5]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-02-01 00:17:35,2020-02-01 00:30:32,1,2.60,1,N,145,7,1,11.0,0.5,0.5,2.45,0.0,0.3,14.75,0.0
1,1,2020-02-01 00:32:47,2020-02-01 01:05:36,1,4.80,1,N,45,61,1,21.5,3.0,0.5,6.30,0.0,0.3,31.60,2.5
2,1,2020-02-01 00:31:44,2020-02-01 00:43:28,1,3.20,1,N,186,140,1,11.0,3.0,0.5,1.00,0.0,0.3,15.80,2.5
3,2,2020-02-01 00:07:35,2020-02-01 00:31:39,1,4.38,1,N,144,140,1,18.0,0.5,0.5,3.00,0.0,0.3,24.80,2.5
4,2,2020-02-01 00:51:43,2020-02-01 01:01:29,1,2.28,1,N,238,152,2,9.5,0.5,0.5,0.00,0.0,0.3,10.80,0.0

In [6]:
df["VendorID"]

0     1
1     1
2     1
3     2
4     2
     ..
95    2
96    1
97    1
98    1
99    1
Name: VendorID, Length: 100, dtype: int64

In [7]:
df["tpep_pickup_datetime"]

0     2020-02-01 00:17:35
1     2020-02-01 00:32:47
2     2020-02-01 00:31:44
3     2020-02-01 00:07:35
4     2020-02-01 00:51:43
             ...
95    2020-02-01 00:54:28
96    2020-02-01 00:05:13
97    2020-02-01 00:47:54
98    2020-02-01 00:54:04
99    2020-02-01 00:16:58
Name: tpep_pickup_datetime, Length: 100, dtype: str

In [8]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

df = pd.read_csv(prefix + "yellow_tripdata_2020-02.csv.gz",
           nrows = 100,
           dtype = dtype,
           parse_dates = parse_dates)

In [9]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2020-02-01 00:17:35,2020-02-01 00:30:32,1,2.60,1,N,145,7,1,11.0,0.5,0.5,2.45,0.0,0.3,14.75,0.0
1,1,2020-02-01 00:32:47,2020-02-01 01:05:36,1,4.80,1,N,45,61,1,21.5,3.0,0.5,6.30,0.0,0.3,31.60,2.5
2,1,2020-02-01 00:31:44,2020-02-01 00:43:28,1,3.20,1,N,186,140,1,11.0,3.0,0.5,1.00,0.0,0.3,15.80,2.5
3,2,2020-02-01 00:07:35,2020-02-01 00:31:39,1,4.38,1,N,144,140,1,18.0,0.5,0.5,3.00,0.0,0.3,24.80,2.5
4,2,2020-02-01 00:51:43,2020-02-01 01:01:29,1,2.28,1,N,238,152,2,9.5,0.5,0.5,0.00,0.0,0.3,10.80,0.0

In [10]:
df["tpep_pickup_datetime"]

0    2020-02-01 00:17:35
1    2020-02-01 00:32:47
2    2020-02-01 00:31:44
3    2020-02-01 00:07:35
4    2020-02-01 00:51:43
             ...
95   2020-02-01 00:54:28
96   2020-02-01 00:05:13
97   2020-02-01 00:47:54
98   2020-02-01 00:54:04
99   2020-02-01 00:16:58
Name: tpep_pickup_datetime, Length: 100, dtype: datetime64[us]

In [18]:
!uv add sqlalchemy

Resolved 116 packages in 1.82s
Prepared 2 packages in 172ms
░░░░░░░░░░░░░░░░░░░░ [0/2] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 2 packages in 203ms
 + greenlet==3.5.1
 + sqlalchemy==2.0.50

In [14]:
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [20]:
pd.io.sql.get_schema(df, name="yellow_taxi_data", con=engine)

'\nCREATE TABLE yellow_taxi_data (\n\t"VendorID" BIGINT, \n\ttpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE, \n\ttpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE, \n\tpassenger_count BIGINT, \n\ttrip_distance FLOAT(53), \n\t"RatecodeID" BIGINT, \n\tstore_and_fwd_flag TEXT, \n\t"PULocationID" BIGINT, \n\t"DOLocationID" BIGINT, \n\tpayment_type BIGINT, \n\tfare_amount FLOAT(53), \n\textra FLOAT(53), \n\tmta_tax FLOAT(53), \n\ttip_amount FLOAT(53), \n\ttolls_amount FLOAT(53), \n\timprovement_surcharge FLOAT(53), \n\ttotal_amount FLOAT(53), \n\tcongestion_surcharge FLOAT(53)\n)\n\n'

In [22]:
df.head(n=0).to_sql(name="yellow_taxi_data", con=engine, if_exists='replace')

0

In [17]:
df_iter= pd.read_csv(
    prefix + "yellow_tripdata_2020-02.csv.gz",
    dtype=dtype,
    parse_dates=parse_dates,
    chunksize = 100000
)

In [ ]:
for df_chunk in df_iter:
    print(len(df_chunk))

In [26]:
!uv add tqdm

Resolved 117 packages in 1.26s
Prepared 1 package in 33ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 23ms
 + tqdm==4.67.3

In [12]:
from tqdm.auto import tqdm

In [ ]:
first = True

for df_chunk in tqdm(df_iter):
    print("Processing chunk of size:", len(df_chunk))

    #Create the Table if it doesn't exists
    if first:
        df_chunk.head(n=0).to_sql(
            name="yellow_taxi_data",
            con=engine,
            if_exists="replace")

        first = False

    #Insert data
    df_chunk.to_sql(
        name="yellow_taxi_data",
        con=engine,
        if_exists="append")

    print("Inserted:", len(df_chunk))

0it [00:00, ?it/s]

Processing chunk of size: 100000
Inserted: 100000
Processing chunk of size: 100000
Inserted: 100000
Processing chunk of size: 100000